'use strict';
// `repo-ready check` — audits an existing AGENTS.md against the live repo:
// do documented commands still exist? is the doc missing new scripts/dirs? is it ours and how old?
const fs = require('fs');
const path = require('path');
const { AGENTS_FILE, START } = require('./generate');
const { extract } = require('./commands');
const { scanTree } = require('./structure');

function backtickCommands(md, section) {
  // commands listed as `...` inside a given "## <title>" section
  const rx = new RegExp(`##\\s+${section}[\\s\\S]*?(?=\\n##\\s|$)`, 'i');
  const m = md.match(rx);
  if (!m) return [];
  return [...m[0].matchAll(/`([^`]+)`/g)].map((x) => x[1]).filter((c) => /\s/.test(c) || /\w+(-\w+)*( \w+)*$/.test(c));
}

function check(root, profile, commands) {
  const file = path.join(root, AGENTS_FILE);
  const report = { file, exists: fs.existsSync(file), issues: [], warnings: [], good: [], score: 100 };

  if (!report.exists) {
    report.score = 0;
    report.issues.push('AGENTS.md does not exist — AI agents have zero context about this repo');
    report.verdict = 'missing';
    return report;
  }
  const md = fs.readFileSync(file, 'utf8');

  // Is it repo-ready managed?
  const hasMarkers = md.includes(START);
  const ver = md.match(/repo-ready:auto-start \(v([^)]+)\)/);
  if (hasMarkers) {
    report.good.push(`repo-ready managed (v${ver ? ver[1] : '?'})`);
    if (ver && ver[1] !== require('../package.json').version) {
      report.warnings.push(`generated by repo-ready v${ver[1]}, current CLI is v${require('../package.json').version}`);
    }
  } else {
    report.warnings.push('AGENTS.md exists but is not repo-ready managed — commands below are audited anyway');
  }

  // 1. Do documented commands still exist?
  const documented = backtickCommands(md, 'Commands');
  const available = new Set(commands.map((c) => c.cmd));
  const scripts = (() => { try { return Object.keys(JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).scripts || {}); } catch { return []; } })();
  const isNpmRun = (c) => /^npm (run )?[\w:.-]+$/.test(c) || /^npm (run )?install$/.test(c);

  for (const cmd of documented) {
    if (available.has(cmd)) { report.good.push(`command OK: \`${cmd}\``); continue; }
    const alias = cmd.replace(/^npm run /, '');
    if (isNpmRun(cmd) && !scripts.includes(alias)) {
      report.score -= 25;
      report.issues.push(`documented command \`${cmd}\` no longer exists in package.json scripts`);
    } else if (!isNpmRun(cmd)) {
      report.score -= 10;
      report.warnings.push(`documented command \`${cmd}\` was not found in current manifests (may be fine if run by hand)`);
    } else {
      report.good.push(`command OK: \`${cmd}\``);
    }
  }
  if (!documented.length && commands.length) {
    report.score -= 25;
    report.issues.push('no Commands section found, but this repo has runnable commands agents should know');
  }

  // 2. New scripts not documented
  const missingScripts = scripts.filter((s) => !['test', 'dev', 'build', 'lint'].includes(s) && !md.includes(`npm run ${s}`) && !['prepare', 'postinstall', 'preinstall'].includes(s));
  if (missingScripts.length) {
    report.score -= 10;
    report.warnings.push(`package.json has scripts not documented in AGENTS.md: ${missingScripts.map((s) => '`' + s + '`').join(', ')}`);
  }

  // 3. Top-level dirs not mentioned
  const tree = scanTree(root, 1);
  const topLevel = tree.split('\n').slice(1).map((l) => l.trim()).filter((l) => l.endsWith('/')).map((l) => l.slice(0, -1));
  const notMentioned = topLevel.filter((d) => !md.includes(d));
  if (notMentioned.length) {
    report.score -= 5 * notMentioned.length;
    report.warnings.push(`directories not mentioned in AGENTS.md: ${notMentioned.map((d) => '`' + d + '/`').join(', ')}`);
  }

  // 4. New commands visible in CI but not in doc
  const ciCmds = extract(root, profile).filter((c) => c.source.includes('CI'));
  for (const c of ciCmds) {
    if (!md.includes(c.cmd)) {
      report.score -= 10;
      report.warnings.push(`CI runs \`${c.cmd}\` but AGENTS.md does not mention it`);
    }
  }

  report.score = Math.max(0, Math.min(100, report.score));
  report.verdict = report.score >= 90 ? 'healthy' : report.score >= 60 ? 'stale' : 'critical';
  report.hint = report.verdict === 'healthy'
    ? null
    : `run \`npx repo-ready update\` to regenerate the managed block (your manual notes outside the markers are preserved)`;
  return report;
}

function format(report) {
  const icon = { healthy: '✅', stale: '🟡', critical: '🔴', missing: '❌' }[report.verdict];
  const lines = [`\n  ${icon} Repo health: ${report.verdict.toUpperCase()} (${report.score}/100)\n`];
  for (const g of report.good) lines.push(`   ✅ ${g}`);
  for (const w of report.warnings) lines.push(`   ⚠️  ${w}`);
  for (const i of report.issues) lines.push(`   ❌ ${i}`);
  if (report.hint) lines.push(`\n   💡 ${report.hint}`);
  lines.push('');
  return lines.join('\n');
}

module.exports = { check, format };
