'use strict';
// AGENTS.md / CLAUDE.md generation with auto-block markers:
// everything between the markers is owned by repo-ready; manual notes outside are preserved.
const fs = require('fs');
const path = require('path');

const VERSION = require('../package.json').version;
const START = `<!-- repo-ready:auto-start (v${VERSION}) — everything in this block is regenerated by \`npx repo-ready update\`. Your notes below stay safe. -->`;
const END = '<!-- repo-ready:auto-end -->';
const AGENTS_FILE = 'AGENTS.md';
const CLAUDE_FILE = 'CLAUDE.md';

function fmtDate() {
  return new Date().toISOString().slice(0, 10);
}

function bulletList(items) { return items.map((i) => `- ${i}`).join('\n'); }

function render(profile, commands, tree, envs, guards) {
  const L = [];
  const stack = [...profile.languages];
  const stackLine = [
    stack.length ? `**Languages:** ${stack.join(', ')}` : null,
    profile.frameworks.length ? `**Frameworks:** ${profile.frameworks.join(', ')}` : null,
    profile.tools.length ? `**Tooling:** ${profile.tools.join(', ')}` : null,
    profile.packageManagers.length ? `**Package managers:** ${profile.packageManagers.join(', ')}` : null,
  ].filter(Boolean);

  L.push(`# ${profile.name}`);
  L.push('');
  L.push(profile.description ? `> ${profile.description}` : '> ' + 'Instructions for AI coding agents (Claude Code, Codex, Cursor, ...). Read this file fully before making changes.');
  L.push('');

  L.push('## Tech stack');
  L.push('');
  L.push(stackLine.map((s) => `- ${s}`).join('\n'));
  if (profile.monorepo) {
    L.push(`- **Monorepo** (${profile.monorepo.kind})${profile.monorepo.packages.length ? `: ${profile.monorepo.packages.join(', ')}` : ''}`);
  }
  if (profile.infra.docker) L.push('- **Docker** present — prefer container commands when they exist');
  if (profile.infra.ci) L.push('- **CI** present — the commands below are validated against what CI actually runs');
  L.push('');

  if (commands.length) {
    L.push('## Commands');
    L.push('');
    L.push('| Purpose | Command | Confidence |');
    L.push('|---|---|---|');
    for (const c of commands) L.push(`| ${c.purpose} | \`${c.cmd}\` | ${c.source} |`);
    L.push('');
  }

  L.push('## Repository layout');
  L.push('');
  L.push('```');
  L.push(tree);
  L.push('```');
  L.push('');

  if (envs.length) {
    L.push('## Environment variables');
    L.push('');
    L.push('Copy `.env.example` → `.env` before running. Required keys:');
    L.push('');
    L.push(envs.map((e) => `- \`${e.key}\`${e.comment ? ` — ${e.comment}` : e.hasValue ? '' : ' — no default, must be set'}`).join('\n'));
    L.push('');
  }

  if (profile.tools.some((t) => ['ESLint', 'Prettier', 'ruff', 'Black', 'Biome'].includes(t))) {
    L.push('## Code style');
    L.push('');
    L.push(bulletList([
      profile.infra.prettier ? 'Formatting is enforced by Prettier — run the format command before committing' : null,
      profile.infra.eslint ? 'Linting via ESLint — treat lint errors as failing tests' : null,
      profile.tools.includes('TypeScript') ? 'TypeScript — prefer fixing types over `any` casts' : null,
      profile.tools.includes('ruff') ? 'Python lint/format via ruff — run before committing' : null,
      profile.tools.includes('Black') ? 'Formatting via Black' : null,
      profile.tools.includes('Jest') || profile.tools.includes('Vitest') || profile.tools.includes('pytest') ? 'Add or update tests for any behavior you change' : null,
    ].filter(Boolean)));
    L.push('');
  }

  if (guards.length) {
    L.push('## Do not touch');
    L.push('');
    L.push(bulletList(guards));
    L.push('');
  }

  L.push('## Definition of done');
  L.push('');
  const testCmd = commands.find((c) => c.purpose === 'test');
  const lintCmd = commands.find((c) => c.purpose === 'lint');
  const buildCmd = commands.find((c) => c.purpose === 'build');
  L.push(bulletList([
    testCmd ? `Run \`${testCmd.cmd}\` and make it pass before claiming a task is done` : 'Run the test suite and make it pass before claiming a task is done',
    lintCmd ? `Run \`${lintCmd.cmd}\` — zero new warnings` : null,
    buildCmd ? `Make sure \`${buildCmd.cmd}\` still succeeds` : null,
    'Do not commit unless the user asked for a commit',
    'Summarize at the end: what changed, what you verified, what is left',
  ].filter(Boolean)));
  L.push('');

  return L.join('\n');
}

function renderClaude(profile) {
  return [
    `# CLAUDE.md — ${profile.name}`,
    '',
    '<!-- Generated by repo-ready. Keep project instructions in AGENTS.md; this file only bridges Claude-specific config. -->',
    '',
    '@AGENTS.md',
    '',
    '## Claude Code specifics',
    '',
    '- Follow AGENTS.md above — especially the Commands and "Do not touch" sections.',
    '- Use the Task tool for broad searches instead of reading many files.',
    '- When you modify agent-facing docs (AGENTS.md), re-run `npx repo-ready check` to catch drift.',
  ].join('\n');
}

function wrapAuto(body) { return `${START}\n${body}\n${END}`; }

// Merges new auto content into an existing AGENTS.md, preserving user text outside markers.
function mergeAgentsMd(existing, body) {
  if (!existing) return `${wrapAuto(body)}\n`;
  const startIdx = existing.indexOf(START);
  const endIdx = existing.indexOf(END);
  if (startIdx === -1 || endIdx === -1) {
    // no markers: treat entire old content as manual notes, append auto block
    return `${existing.trimEnd()}\n\n${wrapAuto(body)}\n`;
  }
  const before = existing.slice(0, startIdx).trimEnd();
  const after = existing.slice(endIdx + END.length).trimStart();
  return `${before ? before + '\n\n' : ''}${wrapAuto(body)}${after ? '\n\n' + after : ''}\n`;
}

function write(root, opts = {}) {
  const profile = opts.profile;
  const body = render(profile, opts.commands, opts.tree, opts.envs, opts.guards);
  const agentsPath = path.join(root, AGENTS_FILE);
  const existing = fs.existsSync(agentsPath) ? fs.readFileSync(agentsPath, 'utf8') : null;

  // Foreign file (no markers) needs an explicit decision; our own file just merges.
  const isOurs = !!existing && existing.indexOf(START) !== -1;
  if (existing && !opts.merge && !opts.force && !isOurs) {
    const err = new Error('AGENTS.md already exists. Use --force to overwrite manually-edited file, or run `update` to merge.');
    err.code = 'EXISTS';
    throw err;
  }

  const merged = mergeAgentsMd(existing, body);
  fs.writeFileSync(agentsPath, merged);

  const claudePath = path.join(root, CLAUDE_FILE);
  const claudeNote = `<!-- repo-ready:auto (v${VERSION}, ${fmtDate()}) -->\n`;
  if (!fs.existsSync(claudePath) || opts.force) fs.writeFileSync(claudePath, claudeNote + renderClaude(profile) + '\n');

  return {
    agentsPath,
    claudePath: fs.existsSync(claudePath) ? claudePath : null,
    mergedWithManual: !!(existing && existing.indexOf(START) !== -1),
  };
}

module.exports = { write, render, mergeAgentsMd, wrapAuto, START, END, AGENTS_FILE, CLAUDE_FILE, VERSION };
